let STORE_CONFIG=null; async function loadConfig(){ if(STORE_CONFIG) return STORE_CONFIG; const r=await fetch('/config.json'); STORE_CONFIG=await r.json(); return STORE_CONFIG; }
const CART_KEY='kanjo_cart_live_v1'; function loadCart(){ try{return JSON.parse(localStorage.getItem(CART_KEY))||[];}catch(e){return []} } function saveCart(c){ localStorage.setItem(CART_KEY, JSON.stringify(c)); }
function cartCount(){ return loadCart().reduce((s,i)=>s+i.qty,0); } function updateCartBadge(){ document.querySelectorAll('.nav a[href="/cart.html"]').forEach(a=>a.innerHTML=`Cart (${cartCount()})`); }
function addToCart(item){ const c=loadCart(); const i=c.findIndex(p=>p.id===item.id && JSON.stringify(p.options)===JSON.stringify(item.options)); if(i>-1){c[i].qty+=item.qty}else{c.push(item)}; saveCart(c); updateCartBadge(); alert('Added to cart.'); }
async function renderCart(){ const cfg=await loadConfig(); const list=document.getElementById('cart-list'); const summary=document.getElementById('cart-summary'); if(!list||!summary)return;
  list.innerHTML=''; const cart=loadCart(); let subtotal=0;
  cart.forEach((it,i)=>{ const line=it.price*it.qty; subtotal+=line; const row=document.createElement('div'); row.className='cart-row';
  row.innerHTML=`<div class="cart-col"><img src="/assets/${it.image}" style="width:90px;height:90px;object-fit:cover;border-radius:10px;border:1px solid #1f1f1f"/><div><div style="font-weight:800">${it.name}</div><div class="small">Options: ${Object.entries(it.options||{}).map(([k,v])=>k+': '+v).join(', ')||'—'}</div><div class="small">Unit: ${cfg.store.currency_symbol}${it.price.toFixed(2)} ${cfg.store.currency}</div></div></div><div class="cart-col"><label class="small">Qty</label><input class="input qty" data-i="${i}" type="number" min="1" value="${it.qty}" style="width:90px"/><div class="price">${cfg.store.currency_symbol}${line.toFixed(2)}</div><button class="btn secondary rm" data-i="${i}">Remove</button></div>`; list.appendChild(row); });
  const shipping=subtotal>=cfg.store.free_shipping_threshold||subtotal===0?0:cfg.store.flat_shipping; const tax=(subtotal+shipping)*cfg.store.tax_rate; const total=subtotal+shipping+tax;
  summary.innerHTML=`<div class="total-box"><div>Subtotal</div><div>${cfg.store.currency_symbol}${subtotal.toFixed(2)} ${cfg.store.currency}</div></div><div class="total-box"><div>Shipping</div><div>${shipping===0?'Free':cfg.store.currency_symbol+shipping.toFixed(2)}</div></div><div class="total-box"><div>Tax</div><div>${cfg.store.currency_symbol}${tax.toFixed(2)}</div></div><div class="total-box" style="font-size:20px;font-weight:900"><div>Total</div><div>${cfg.store.currency_symbol}${total.toFixed(2)} ${cfg.store.currency}</div></div><div style="display:flex;gap:12px;margin-top:10px;"><a class="btn" href="/checkout.html">Checkout</a></div><div class="small muted">Free shipping over ${cfg.store.currency_symbol}${cfg.store.free_shipping_threshold.toFixed(2)}.</div>`;
  document.querySelectorAll('.qty').forEach(inp=>inp.addEventListener('change',e=>{const i=parseInt(e.target.dataset.i); const c=loadCart(); c[i].qty=Math.max(1,parseInt(e.target.value||'1')); saveCart(c); renderCart(); updateCartBadge();}));
  document.querySelectorAll('.rm').forEach(btn=>btn.addEventListener('click',e=>{const i=parseInt(e.target.dataset.i); const c=loadCart(); c.splice(i,1); saveCart(c); renderCart(); updateCartBadge();})); } document.addEventListener('DOMContentLoaded', updateCartBadge);